export const quotes = [
  {
    quote:
      "There isn't supposed to be a testimonial section 'cause It's quite new. So uh... yeah...",
  },
  {
    quote: "I just didn't want to remove this part 'cause it looks good 🤣",
  },
  {
    quote:
      'this website is generated by v0 and modified by yours truly. Pretty nice... looks like a SASS website though, but who cares?',
  },
];
